"""m-4

Revision ID: 3bfa2f3314ba
Revises: d5561e8cdf71
Create Date: 2020-12-05 03:16:50.570013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfa2f3314ba'
down_revision = 'd5561e8cdf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bell', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('bell')

    # ### end Alembic commands ###
